version: "3.9"

services:
  postgres:
    image: postgres:14.8-alpine
    environment:
      POSTGRES_DB: "triangle_desktop_app"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # RabbitMQ Management Dashboard
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq