"""Add triangle table

Revision ID: e746c3c3081b
Revises: 174f1eba6a3d
Create Date: 2023-12-05 22:38:35.532346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e746c3c3081b'
down_revision: Union[str, None] = '174f1eba6a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triangles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_side', sa.Float(), nullable=True),
    sa.Column('second_side', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triangles')
    # ### end Alembic commands ###
